Force XCode version for macos15 build (#1633)
After recent changes in runners environment current setup is giving
error: iOS 18.0 Platform Not Installed

Relates-To: MINOR

Signed-off-by: Rustam Gamidov <ext-rustam.gamidov@here.com>